# -*- coding: utf-8 -*-
"""김예진GBT0522.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/158NAnLNUdUuWq_9IJGXJ6A9Qq8yTEY3t

# 문자열의 분리 split()
"""

colors = ['red', 'blue', 'green', 'yellow']
result = ''.join(colors)
print(result)

ex = 'python,math,toeic'
print(ex.split(','))

ex = 'python,math,toeic'
a, b, c = ex.split(',')
print(a, b, c)

ex2 = 'python.univ.edu'
subdomain, domain, tld = ex2.split('.')
print(subdomain, domain, tld)

"""# 문자열의 결합 join() 함수"""

colors = ['red', 'blue', 'green', 'yellow']
result = ', '.join(colors)
print(result)

colors = ['red', 'blue', 'green', 'yellow']
result = ' '.join(colors)
print(result)

colors = ['red', 'blue', 'green', 'yellow']
result = ''.join(colors)
print(result)

colors = ['red', 'blue', 'green', 'yellow']
result = '-'.join(colors)
print(result)

"""# 리스트의 함축 표현 list comprehension"""

result = []
for i in range(10):
    result.append(i)

print(result)

result = [i for i in range(10)]
print(result)

result = [i+1 for i in range(10)]
print(result)

result = [(i+1)**2 for i in range(10)]
print(result)

result = [i for i in range(1, 11)]
print(result)

#짝수 출력
result = []
for i in range(10):
    if i%2 == 0:
        result.append(i)
print(result)

result = [i for i in range(1, 11)  if i%2 == 0]
print(result)

#리스트 함축표현 if~else
result = [i if i%2 ==0 else '홀수' for i in range(1, 11)]
print(result)

#리스트 함축표현 if~else -> 홀수자리마다 10으로 표시
result = [i if i%2 ==0 else '10' for i in range(1, 11)]
print(result)

#중첩 for문을 함축 리스트로
word1 = "Hello"
word2 = "World"
result = [i + j for i in word1 for j in word2]
print(result)
print(len(result))

#이차원 리스트
text = 'The quick brown fox jumps over the lazy dog'
words = text.split()
print(words)
print(len(words))

stuff = [w for w in words]
print(stuff)

stuff = [[w.upper(), w.lower()] for w in words]
print(stuff)

stuff = [[w.upper()] for w in words]
print(stuff)

stuff = [[w.lower()] for w in words]
print(stuff)

stuff = [[w.upper(), w.lower(), len(w)] for w in words]
print(stuff)

for i in stuff:
    print(i)

case_1 = ["A", "B", "C"]
case_2 = ["D", "E", "A"]
result = [i + j for i in case_1 for j in case_2]
print(result)

result = [[i+j for i in case_1] for j in case_2]
print(result)

"""# enumerate() 함수"""

for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

text = 'TEAMLAB is an academic institute located in South Korea.'
{i:j for i, j in enumerate(text.split())}

r = {i:v for i,v in enumerate(text.split())}
print(r)
print(len(r))

"""# 리스트 값을 병렬로 묶어 출력: zip() 함수"""

alist = ['a1', 'a2', 'a3']
blist = ['b1', 'b2', 'b3']
for a, b in zip(alist, blist):
    print(a,b)

a,b,c = zip((1,2,3), (10,20,30), (100,200,300))
print(a,b,c)

[sum(x) for x in zip((1,2,3), (10,20,30), (100,200,300))]

alist = ['a1', 'a2', 'a3']
blist = ['b1', 'b2', 'b3']
for idx, (a, b) in enumerate(zip(alist, blist)):    #괄호 없으면 ValueError뜸 - 패킹 언패킹?
    print(idx, a,b)

"""# 람다함수 lambda"""

def f(x,y):
    return x+y

print(f(1,4))

f = lambda x, y:x+y
print(f(1,4))

f = lambda x, y:x*y
print(f(2,4))

f = lambda x, y:x**y
print(f(2,4))

#왜 오류? x밖에 없는데 전달되는 값은 2개라서
f = lambda x:x+1
print(f(2, 4))

f = lambda x:x+1
print(f(4))

print((lambda x:x+1)(4))

print((lambda x,y:x+y)(2,4))

print((lambda x,y:x*y)(2,4))

print((lambda x,y:x**y)(2,4))

print((lambda x,y:y//2)(2,4))

print((lambda x,y:y%x)(2,4))

"""# map() 함수"""

ex = [1,2,3,4,5]
f = lambda x: x**2
print(list(map(f, ex)))

ex = [1,2,3,4,5]
result = [x**2 for x in ex]
print(result)

ex = [1,2,3,4,5]
dx = [10,20,30,40,50]
f = lambda x,y:x+y
list(map(f,ex,dx))

ex = [1,2,3,4,5]
dx = [10,20,30,40,50]
[x+y for x, y in zip(ex, dx)]

ex = [1,2,3,4,5]
f = lambda x: x**2 if x%2 == 0 else x
list(map(f,ex))

[x**2 if x%2 ==0 else x for x in ex]

